### ISSUE TITLE
macOS Monterey

### ISSUE THREAD

**Issue by donavanbecker** [sonsongithub/SBMeter#1]
How do you set this up?

<img width="126" alt="Screen Shot 2021-10-10 at 6 49 12 AM" src="https://user-images.githubusercontent.com/9875439/136694282-8e530c93-3851-4284-b247-fa218701ef4d.png">

**Comment by sonsongithub** [comment]
Please turn on bluetooth on macOS and SwitchBot meter.

Maybe... In the "Security and privacy" section of the Settings app, you may need to give SBMeter permission to use bluetooth.
You do not prepare anything because this app uses only BLE advertisement packets.

**Comment by donavanbecker** [comment]
thanks for your help. I tried that, but nothing is showing up. On macOS Monterey Beta 9.

**Comment by sonsongithub** [comment]
Sorry, I tried SBMeter again, it works well on Big Sur.
The issue may be caused on macOS version.
I will investigate it after be released Monterey.

**Comment by donavanbecker** [comment]
Sounds good! Thanks!

**Comment by sonsongithub** [comment]
I have confirmed this problem. Thank you for reporting.

**Comment by sonsongithub** [comment]
This seems to be a bug in the Monterey....
https://github.com/hbldh/bleak/issues/635

**Comment by donavanbecker** [comment]
@sonsongithub, for the time being could you add an option to set a specific MAC address? So it can communicate with the meters?

I think the issue is just with discovering not communicating.

**Comment by sonsongithub** [comment]
You mean service ID...?

**Comment by sonsongithub** [comment]
Oh! I have fixed it, right now!

**Comment by donavanbecker** [comment]
@sonsongithub Are you pushing out a new version then?

**Comment by sonsongithub** [comment]
Please wait... it's midnight now... And, I'm having a hard time notarazing the app....

**Comment by sonsongithub** [comment]
I've just released the fixed version.
